version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t my-image .
            docker push my-image

workflows:
  version: 2
  build_and_push:
    jobs:
      - build